[defaults]
version = "latest"
noarch = true
build_args = [] # --noarch will automatically be added if applicable
# The below will only be used if noarch is False
pythons = ["3.6", "3.7", "3.8"]
platforms = ["win-32", "win-64", "osx", "linux"]


[spinapi]

[PyDAQmx]
build_args = ['--license-file=None']

[pyqtgraph]
version = '0.11.0rc0'

[pynivision]
build_args = ['--license-file=None']
