[defaults]
version = "latest"
source = "pypi"
noarch = true
build_args = [] # --noarch will automatically be added if applicable
# The below will only be used if noarch is False
pythons = ["3.9", "3.10", "3.11", "3.12", "3.13"]
platforms = ["win-64", "osx-64", "linux"]


[spinapi]
# TODO: configure spinapi to build and release itself since we own it

[PyDAQmx]
build_args = ['--license-file=None']

[pynivision]
# TODO: We own pynivision now, so we should release it the normal way.
build_args = ['--license-file=None']

[windows-curses]
source = "git+https://github.com/zephyrproject-rtos/windows-curses/"
noarch = false
build_args = ['--from-downloaded-wheel']
platforms = ["win-64"]

[PyVISA]
