name: Make and upload Conda packages

on:
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    # - cron: '0-59/5 * * * *' # Every 5 minutes
    - cron: '0 02 * * 0' # Weekly, 2AM Sundays UTC

env:
  ANACONDA_USER: labscript-suite

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    if: github.repository == 'labscript-suite/vendored-conda-builds'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout latest tag
        if: github.event_name == 'schedule'
        shell: bash -l {0}
        run: git checkout $(git describe --tags `git rev-list --tags --max-count=1`)

      - name: Set BUILD_NOARCH=true
        if: strategy.job-index == 0
        shell: bash -l {0}
        run: echo "BUILD_NOARCH=true" >> $GITHUB_ENV

      - name: Install Miniforge
        uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          conda-remove-defaults: true
          auto-activate: true
          activate-environment: ""

      - name: Conda package
        shell: bash -l {0}
        run: |
          CONDA_BUILD_ARGS=""
          if [ "${{ runner.os }}" == Windows ]; then
            # Short path to minimise odds of hitting Windows max path length
            CONDA_BUILD_ARGS+=" --croot ${{ runner.temp }}\cb"
          fi
          conda install -c labscript-suite setuptools-conda
          python make_packages.py "${{ runner.temp }}" $CONDA_BUILD_ARGS

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: conda_packages-${{ matrix.os }}
          path: ./conda_packages
          if-no-files-found: error

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          pattern: conda_packages-*
          path: ./conda_packages
          merge-multiple: true

      - name: Install Miniforge
        uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          conda-remove-defaults: true
          auto-activate: true
          activate-environment: ""

      - name: Install Anaconda cloud client
        shell: bash -l {0}
        run: conda install anaconda-client

      # - name: Publish to Anaconda test label
      #   if: github.event.ref_type != 'tag' && github.event_name != 'schedule'
      #   shell: bash -l {0}
      #   run: |
      #     anaconda \
      #       --token ${{ secrets.ANACONDA_API_TOKEN }} \
      #       upload \
      #       --user $ANACONDA_USER \
      #       --label test \
      #       --skip-existing \
      #       conda_packages/*/*

      - name: Publish to Anaconda main label
        if: (github.event_name == 'push' && contains(github.ref, '/tags')) || github.event_name == 'schedule'
        shell: bash -l {0}
        run: |
          anaconda \
            --token ${{ secrets.ANACONDA_API_TOKEN }} \
            upload \
            --user $ANACONDA_USER \
            --skip-existing \
            conda_packages/*/*
